export { default as Logo } from './logo'
export { default as Arrown } from './arrown'
export { default as Plus } from './plus'
export { default as Minus } from './minus'
export { default as Close } from './close'
export { default as Tarjetas } from './tarjetas'
export { default as Transfers } from './transfers'
export { default as Home } from './home'
