import './globals.css'
import type { Metadata } from 'next'
import { Suspense } from 'react'
import { ReactQueryProvider, SessionAuthProvider } from './providers'

export const metadata: Metadata = {
  description: 'Generated by create next app',
  title: 'Create Next App',
}

const RootLayout = ({ children }: { children: React.ReactNode }) => {
  return (
    <html lang='en'>
      <body>
        <ReactQueryProvider>
          <SessionAuthProvider>
            <Suspense fallback={<div>Loading...</div>}>{children}</Suspense>
          </SessionAuthProvider>
        </ReactQueryProvider>
      </body>
    </html>
  )
}

export default RootLayout
