export const codesEnabled: Record<string, boolean> = {
  ACCOUNT: true,
  CONSOLIDADA: true,
  CREDIT: true,
  CREDIT_DETAIL: true,
  CREDIT_PURCHASE: true,
  CUENTAS_DETALLE: true,
  DEBIT: true,
  LOGIN: true,
  LOGIN_CREDENTIALS: true,
  LOGIN_PHONE: true,
  LOGIN_PHONE_VERIFY: true,
  LOGIN_VALIDATE_CODE: true,
  LOGIN_VERIFY_GOOGLE: true,
  MOV_ACCOUNT: true,
  NOT_FOUND: true,
  ON_BOARDING: true,
  PERFIL: true,
  RECEIPTS: true,
  RECEIPTSID: true,
  REGISTER: true,
  REGISTER_CRED: true,
  REGISTER_CRED_CODE: true,
  REGISTER_CRED_CONFIRM: true,
  ROULETTE: true,
  STORE: true,
  TRANSFER: true,
}
